### ISSUE TITLE
Merge designdata and subscriptiondata to create an analysis file.

### ISSUE THREAD

**Issue by jwbowers** [sbstusa/oneblast#1]
We need to create the outcome by merging the designdata.csv and the subscriptiondata.csv. The idea is anyone from designdata who is not in subscriptiondata did not subscribe to the newsletter. (With the caveat that, actually, we don’t know how many subscribed with different email addresses than those given in designdata). Note further that the email addresses are now just hashes — this allows you to download and work with the files on your own computer.

**Comment by PTesta** [comment]
I've uploaded a file that matches the hashed emails in the design data to the the subscription data and does some initial analysis.
